# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfctl < Formula
  desc "CLI to query Terraform/OpenTofu state across backends"
  homepage "https://github.com/tfctl/tfctl"
  version "1.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tfctl/homebrew-tfctl/releases/download/v1.4.0/tfctl_1.4.0_darwin_x86_64.tar.gz"
      sha256 "29353f3261bcff5eaa83db44a05b4f675bfcc60553daa9aeef8734c851624dca"

      define_method(:install) do
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tfctl/homebrew-tfctl/releases/download/v1.4.0/tfctl_1.4.0_darwin_arm64.tar.gz"
      sha256 "9ef0a3867d040e7552b947ad47aa8af21156aae5fd09d6507d91b05f3b01d62e"

      define_method(:install) do
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tfctl/homebrew-tfctl/releases/download/v1.4.0/tfctl_1.4.0_linux_x86_64.tar.gz"
      sha256 "e21e375e946ca4249902d25bab950d8712b1fbf2ab40054bca67f6d98d4224dc"
      define_method(:install) do
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tfctl/homebrew-tfctl/releases/download/v1.4.0/tfctl_1.4.0_linux_arm64.tar.gz"
      sha256 "e99f6e1fa673cc4a3fd3eb258ff7bffb4f3139c0bb2b2a80d20003de0906a49c"
      define_method(:install) do
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
  end

  test do
    system "#{bin}/tfctl", "--version"
  end
end
