# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfctl < Formula
  desc "CLI to query Terraform/OpenTofu state across backends"
  homepage "https://github.com/tfctl/tfctl"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tfctl/homebrew-tfctl/releases/download/v1.0.0/tfctl_1.0.0_darwin_x86_64.tar.gz"
      sha256 "d4c6d59709ddd02c3ab187f5efb6c76759e14fe125961019f56799298624d59e"

      def install
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tfctl/homebrew-tfctl/releases/download/v1.0.0/tfctl_1.0.0_darwin_arm64.tar.gz"
      sha256 "76f14f0da1a9b7becfb16386755f8696479491d2fc73d57207a91f68cde1c240"

      def install
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tfctl/homebrew-tfctl/releases/download/v1.0.0/tfctl_1.0.0_linux_x86_64.tar.gz"
      sha256 "8fef9038d0bf41e122b7422b40ad8a9b5e310acf13e749bec3539e91411d3fd1"
      def install
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tfctl/homebrew-tfctl/releases/download/v1.0.0/tfctl_1.0.0_linux_arm64.tar.gz"
      sha256 "d15e50cf7464492e1988ac5d892185887e187618be7428ebfc0bb3989cc72741"
      def install
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
  end

  test do
    system "#{bin}/tfctl", "--version"
  end
end
