# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfctl < Formula
  desc "CLI to query Terraform/OpenTofu state across backends"
  homepage "https://github.com/tfctl/tfctl"
  version "0.99.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tfctl/homebrew-tfctl/releases/download/v0.99.5/tfctl_0.99.5_darwin_x86_64.tar.gz"
      sha256 "decc10ecc5288c2cc235e6493c46274e02c6b01fa6c726a09d96affead69daa8"

      def install
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tfctl/homebrew-tfctl/releases/download/v0.99.5/tfctl_0.99.5_darwin_arm64.tar.gz"
      sha256 "7a9adabee36e4620ff25cd6789725af16a77795cac6f8f9a095f1c93296148d6"

      def install
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tfctl/homebrew-tfctl/releases/download/v0.99.5/tfctl_0.99.5_linux_x86_64.tar.gz"
      sha256 "1b59860895b01730534bfe08b25f850e345e1b2b82aadc86018a4cb93a21284d"
      def install
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tfctl/homebrew-tfctl/releases/download/v0.99.5/tfctl_0.99.5_linux_arm64.tar.gz"
      sha256 "a5c77a8db21889434572b0c8f8fb67c411d0d2f84e5c2827d0fecf3d791eecc7"
      def install
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
  end

  test do
    system "#{bin}/tfctl", "--version"
  end
end
